{
 "title": "zapp服务监控",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "数据源", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "LOKI日志服务", "query": "loki" },
   { "name": "app", "label": "应用名", "query": { "query": "label_values(app)" } },
   {
    "name": "env",
    "label": "环境名",
    "query": {
     "query": "label_values({app=~\"$app\"},env)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "请求总量（1m）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_started_total{app=~\"$app\",env=~\"$env\"}[1m])) ",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "成功率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\", code_type=\"success\"}[1m])) / sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\"}[1m]))",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "异常率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\", code_type!=\"success\"}[1m])) / sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\"}[1m]))",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "超时率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\", code_type=\"timeoutOrCancel\"}[1m])) / sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\"}[1m]))",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{app=~\"$app\", env=~\"$env\"}[5m])) / sum(process_cpu_cores{app=~\"$app\", env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Memory使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{app=~\"$app\",env=~\"$env\"}/process_memory_quota{app=~\"$app\",env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Panic数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_panic_total{app=~\"$app\", env=~\"$env\"}[$__range]))"
    }
   ]
  },
  { "title": "基础信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "环境数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(count(process_cpu_cores{app=~\"$app\"}) by (env))",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "节点数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(process_cpu_cores{app=~\"$app\",env=~\"$env\"})",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CPU配额",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_cores{app=~\"$app\", env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Memory配额",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_memory_quota{app=~\"$app\", env=~\"$env\"}) "
    }
   ]
  },
  {
   "title": "CPU使用核数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{app=~\"$app\", env=~\"$env\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory使用",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{app=~\"$app\", env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "折算单核处理量(QPS)",
   "type": "stat",
   "description": "server请求量/CPU使用量",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_started_total{app=~\"$app\", env=~\"$env\"}[1m]))\n/\nsum(rate(process_cpu_seconds_total{app=~\"$app\", env=~\"$env\"}[1m]))"
    }
   ]
  },
  {
   "title": "上游服务数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\"}[1m])) by (callee_service))",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "上游服务分布",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_started_total{app=~\"$app\",env=~\"$env\"}[$__range])) by (caller_service)",
     "legendFormat": "{{caller_service}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "下游服务数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\"}[1m])) by (callee_service))",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "下游服务分布",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_client_started_total{app=~\"$app\",env=~\"$env\"}[$__range])) by (callee_service)",
     "legendFormat": "{{callee_service}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "版本监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(go_info{app=~\"$app\",env=~\"$env\"}) by (version, instance, container_name)"
    }
   ]
  },
  { "title": "进程监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=~\"$app\",env=~\"$env\"}[1m]) / process_cpu_cores{app=~\"$app\",env=~\"$env\"}",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "avg(\n    rate(process_cpu_seconds_total{app=~\"$app\",env=~\"$env\"}[1m]) / process_cpu_cores{app=~\"$app\",env=~\"$env\"}\n)",
     "legendFormat": "平均值"
    }
   ]
  },
  {
   "title": "Memory使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=~\"$app\",env=~\"$env\"}/process_memory_quota{app=~\"$app\",env=~\"$env\"}",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "process_resident_memory_bytes{app=~\"$app\",env=~\"$env\"}",
     "legendFormat": "usage-{{container_name}}"
    },
    {
     "expr": "avg(\nprocess_resident_memory_bytes{app=~\"$app\",env=~\"$env\"}/process_memory_quota{app=~\"$app\",env=~\"$env\"}\n)",
     "legendFormat": "平均值"
    }
   ]
  },
  {
   "title": "句柄数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "process_open_fds{app=~\"$app\",env=~\"$env\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "重启次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "changes(process_start_time_seconds{app=~\"$app\",env=~\"$env\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "运行时监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "协程数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "go_goroutines{app=~\"$app\",env=~\"$env\"}",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "线程数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "go_threads{app=~\"$app\",env=~\"$env\"}",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "go gc duration",
     "type": "timeseries",
     "description": "gc耗时百分位",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{app=~\"$app\",env=~\"$env\",quantile=\"0.5\"}*1e6",
       "legendFormat": "gc-p50-{{container_name}}"
      },
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "go_gc_duration_seconds{app=~\"$app\",env=~\"$env\",quantile=\"0.75\"}*1e6",
       "legendFormat": "gc-p75-{{container_name}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "expr": "go_gc_duration_seconds{app=~\"$app\",env=~\"$env\",quantile=\"1.0\"}*1e6",
       "legendFormat": "gc-p100-{{container_name}}"
      }
     ]
    },
    {
     "title": "go gc count 1m",
     "type": "timeseries",
     "description": "gc次数",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(go_gc_duration_seconds_count{app=~\"$app\",env=~\"$env\"}[1m])",
       "legendFormat": "gc-count-{{container_name}}"
      }
     ]
    },
    {
     "title": "panic次数 1m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "increase(rpc_server_panic_total{app=~\"$app\",env=~\"$env\",code_type=\"exception\"}[1m])",
       "legendFormat": "{{container_name}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Mem Sys",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "rate(go_memstats_alloc_bytes_total{app=~\"$app\",env=~\"$env\"}[5m])",
       "legendFormat": "alloc_bytes_PerSecond-{{container_name}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "expr": "go_memstats_sys_bytes{app=~\"$app\",env=~\"$env\"}",
       "legendFormat": "sys_bytes-{{container_name}}"
      },
      {
       "expr": "go_memstats_alloc_bytes{app=~\"$app\",env=~\"$env\"}",
       "legendFormat": "alloc_bytes-{{container_name}}"
      }
     ]
    },
    {
     "title": "Mem Heap",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "go_memstats_heap_alloc_bytes{app=~\"$app\",env=~\"$env\"}",
       "legendFormat": "heap_alloc-{{container_name}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{app=~\"$app\",env=~\"$env\"}",
       "legendFormat": "heap_idle-{{container_name}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{app=~\"$app\",env=~\"$env\"}",
       "legendFormat": "heap_inuse-{{container_name}}"
      }
     ]
    },
    {
     "title": "Mem Stack",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "go_memstats_stack_inuse_bytes{app=~\"$app\",env=~\"$env\"}",
       "legendFormat": "stack_inuse-{{container_name}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{app=~\"$app\",env=~\"$env\"}",
       "legendFormat": "stack_sys-{{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "错误日志",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "错误日志",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
     "targets": [
      {
       "expr": "{app=~\"$app\",env=~\"$env\",level=\"error\"}"
      }
     ]
    }
   ]
  },
  { "title": "被调总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "请求总量 1m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\", env=~\"$env\"}[1m]))",
     "legendFormat": "current",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\", env=~\"$env\"}[1m]offset 1d))",
     "legendFormat": "1 day ago"
    },
    {
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\", env=~\"$env\"}[1m]offset 7d))",
     "legendFormat": "7 days ago"
    }
   ]
  },
  {
   "title": "平均耗时",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_handled_msec_sum{app=~\"$app\", env=~\"$env\"}[1m]))/sum(increase(rpc_server_handled_msec_count{app=~\"$app\", env=~\"$env\"}[1m]))",
     "legendFormat": "current",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "expr": "sum(increase(rpc_server_handled_msec_sum{app=~\"$app\", env=~\"$env\"}[1m]offset 1d))/sum(increase(rpc_server_handled_msec_count{app=~\"$app\", env=~\"$env\"}[1m]offset 1d))",
     "legendFormat": "1 day ago"
    },
    {
     "expr": "sum(increase(rpc_server_handled_msec_sum{app=~\"$app\", env=~\"$env\"}[1m]offset 7d))/sum(increase(rpc_server_handled_msec_count{app=~\"$app\", env=~\"$env\"}[1m]offset 7d))",
     "legendFormat": "7 days ago"
    }
   ]
  },
  {
   "title": "异常率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\", env=~\"$env\", code_type!=\"success\"}[1m])) / sum(increase(rpc_server_handled_total{app=~\"$app\", env=~\"$env\"}[1m]))",
     "legendFormat": "current",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\", env=~\"$env\", code_type!=\"success\"}[1m]offset 1d)) / sum(increase(rpc_server_handled_total{app=~\"$app\", env=~\"$env\"}[1m]offset 1d))",
     "legendFormat": "1 day ago"
    },
    {
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\", env=~\"$env\", code_type!=\"success\"}[1m]offset 7d)) / sum(increase(rpc_server_handled_total{app=~\"$app\", env=~\"$env\"}[1m]offset 7d))",
     "legendFormat": "7 days ago"
    }
   ]
  },
  {
   "title": "请求量（服务维度）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\"}[1m])) by (callee_method, callee_service)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "异常率（服务维度）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\",code_type!=\"success\"}[1m])) by (callee_method, callee_service) / sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\"}[1m])) by (callee_method, callee_service)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "耗时P99（服务维度）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "topk(20, histogram_quantile(0.99, sum(rate(rpc_server_handled_msec_bucket{app=~\"$app\",env=~\"$env\"}[1m])) by (le, callee_service, callee_method)))",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "异常返回码（服务维度）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\", code_type!=\"success\"}[1m])) by (callee_method, callee_service, code)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "耗时区间分布(右上角所选时间区间)",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_handled_msec_bucket{app=~\"$app\", env=~\"$env\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "请求量（实例维度）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\"}[1m])) by (instance)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "异常率（实例维度）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\",code_type!=\"success\"}[1m])) by (instance) / sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\"}[1m])) by (instance)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "耗时P99（实例维度）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "topk(20, histogram_quantile(0.99, sum(rate(rpc_server_handled_msec_bucket{app=~\"$app\",env=~\"$env\"}[1m])) by (le, instance)))",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "异常返回码（实例维度）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\", code_type!=\"success\"}[1m])) by (instance, code)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "被调监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "panels": [
    {
     "title": "上游调用监控",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\"}[$__range])) by (caller_service, callee_service, callee_method)",
       "legendFormat": "请求量"
      },
      {
       "expr": "sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\", code_type=\"success\"}[$__range])) by (callee_service, callee_method, caller_service) /  sum(increase(rpc_server_handled_total{app=~\"$app\",env=~\"$env\"}[$__range])) by (callee_service, callee_method, caller_service) ",
       "legendFormat": "成功率"
      },
      {
       "expr": "sum(increase(rpc_server_handled_msec_sum{app=~\"$app\",env=~\"$env\"}[$__range])) by (callee_service, callee_method, caller_service) / sum(increase(rpc_server_handled_msec_count{app=~\"$app\",env=~\"$env\"}[$__range])) by  (callee_service, callee_method, caller_service)",
       "legendFormat": "平均耗时"
      },
      {
       "expr": "topk(20, histogram_quantile(0.99, sum(rate(rpc_server_handled_msec_bucket{app=~\"$app\",env=~\"$env\"}[$__range])) by (le, callee_service, callee_method, caller_service)))",
       "legendFormat": "P99耗时"
      }
     ]
    }
   ]
  },
  {
   "title": "主调总览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "collapsed": true,
   "panels": [
    {
     "title": "请求总量 1m",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(increase(rpc_client_handled_total{app=~\"$app\", env=~\"$env\"}[1m]))",
       "legendFormat": "current",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "expr": "sum(increase(rpc_client_handled_total{app=~\"$app\", env=~\"$env\"}[1m]offset 1d))",
       "legendFormat": "1 day ago"
      },
      {
       "expr": "sum(increase(rpc_client_handled_total{app=~\"$app\", env=~\"$env\"}[1m]offset 7d))",
       "legendFormat": "7 days ago"
      }
     ]
    },
    {
     "title": "平均耗时",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(increase(rpc_client_handled_msec_sum{app=~\"$app\", env=~\"$env\"}[1m]))/sum(increase(rpc_client_handled_msec_count{app=~\"$app\", env=~\"$env\"}[1m]))",
       "legendFormat": "current",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "expr": "sum(increase(rpc_client_handled_msec_sum{app=~\"$app\", env=~\"$env\"}[1m]offset 1d))/sum(increase(rpc_client_handled_msec_count{app=~\"$app\", env=~\"$env\"}[1m]offset 1d))",
       "legendFormat": "1 day ago"
      },
      {
       "expr": "sum(increase(rpc_client_handled_msec_sum{app=~\"$app\", env=~\"$env\"}[1m]offset 7d))/sum(increase(rpc_client_handled_msec_count{app=~\"$app\", env=~\"$env\"}[1m]offset 7d))",
       "legendFormat": "7 days ago"
      }
     ]
    },
    {
     "title": "异常率",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(increase(rpc_client_handled_total{app=~\"$app\", env=~\"$env\", code_type!=\"success\"}[1m])) / sum(increase(rpc_client_handled_total{app=~\"$app\", env=~\"$env\"}[1m]))",
       "legendFormat": "current",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "expr": "sum(increase(rpc_client_handled_total{app=~\"$app\", env=~\"$env\", code_type!=\"success\"}[1m]offset 1d)) / sum(increase(rpc_client_handled_total{app=~\"$app\", env=~\"$env\"}[1m]offset 1d))",
       "legendFormat": "1 day ago"
      },
      {
       "expr": "sum(increase(rpc_client_handled_total{app=~\"$app\", env=~\"$env\", code_type!=\"success\"}[1m]offset 7d)) / sum(increase(rpc_client_handled_total{app=~\"$app\", env=~\"$env\"}[1m]offset 7d))",
       "legendFormat": "7 days ago"
      }
     ]
    },
    {
     "title": "请求量（服务维度）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(increase(rpc_client_handled_total{app=~\"$app\",env=~\"$env\"}[1m])) by (callee_service, callee_method)",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "异常率（服务维度）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(increase(rpc_client_handled_total{app=~\"$app\", env=~\"$env\", code_type!=\"success\"}[1m])) by (callee_service, callee_method)/ sum(increase(rpc_client_handled_total{app=~\"$app\", env=~\"$env\"}[1m])) by (callee_service, callee_method)",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "耗时P99（服务维度）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "topk(20, histogram_quantile(0.99, sum(rate(rpc_client_handled_msec_bucket{app=~\"$app\",env=~\"$env\"}[1m])) by (le, callee_service, callee_method)))",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "异常返回码（服务维度）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(increase(rpc_client_handled_total{app=~\"$app\",env=~\"$env\", code_type!=\"success\"}[1m])) by (code, callee_service, callee_method)",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "耗时区间分布(右上角所选时间区间)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_client_handled_msec_bucket{app=~\"$app\", env=~\"$env\"}[$__range])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "请求量（实例维度）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(increase(rpc_client_handled_total{app=~\"$app\",env=~\"$env\"}[1m])) by (instance)",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "异常率（实例维度）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(increase(rpc_client_handled_total{app=~\"$app\", env=~\"$env\", code_type!=\"success\"}[1m])) by (instance)/ sum(increase(rpc_client_handled_total{app=~\"$app\", env=~\"$env\"}[1m])) by (instance)",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "耗时P99（实例维度）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "topk(20, histogram_quantile(0.99, sum(rate(rpc_client_handled_msec_bucket{app=~\"$app\",env=~\"$env\"}[1m])) by (le, instance)))",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "异常返回码（实例维度）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 78 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(increase(rpc_client_handled_total{app=~\"$app\",env=~\"$env\", code_type!=\"success\"}[1m])) by (code, instance)",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "主调监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "collapsed": true,
   "panels": [
    {
     "title": "调用下游监控",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 170 },
     "targets": [
      {
       "expr": "sum(increase(rpc_client_handled_total{app=~\"$app\",env=~\"$env\"}[$__range])) by (caller_service, caller_method, callee_service, callee_method)",
       "legendFormat": "请求量"
      },
      {
       "expr": "sum(increase(rpc_client_handled_total{app=~\"$app\",env=~\"$env\", code_type=\"success\"}[$__range])) by (callee_service, callee_method, caller_service, caller_method) /  sum(increase(rpc_client_handled_total{app=~\"$app\",env=~\"$env\"}[$__range])) by (callee_service, callee_method, caller_service, caller_method) ",
       "legendFormat": "成功率"
      },
      {
       "expr": "sum(increase(rpc_client_handled_msec_sum{app=~\"$app\",env=~\"$env\"}[$__range])) by (caller_service, caller_method, callee_service, callee_method) / sum(increase(rpc_client_handled_msec_count{app=~\"$app\",env=~\"$env\"}[$__range])) by  (caller_service, caller_method, callee_service, callee_method)",
       "legendFormat": "平均耗时"
      },
      {
       "expr": "topk(20, histogram_quantile(0.99, sum(rate(rpc_client_handled_msec_bucket{app=~\"$app\",env=~\"$env\"}[$__range])) by (le, callee_service, callee_method, caller_service, caller_method)))",
       "legendFormat": "P99耗时"
      }
     ]
    }
   ]
  }
 ]
}