{
 "title": "zapp大盘",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "数据源", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "LOKI日志服务", "query": "loki" },
   { "name": "env", "label": "环境名", "query": { "query": "label_values(env)" } }
  ]
 },
 "panels": [
  {
   "title": "被调总请求(每秒)",
   "type": "stat",
   "description": "所有服务每秒请求量作和",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_started_total{env=~\"$env\"}[1m]))/60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "被调总异常率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_handled_total{env=~\"$env\", code_type!=\"success\"}[1m])) / sum(increase(rpc_server_handled_total{env=~\"$env\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "被调总超时率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_handled_total{env=~\"$env\", code_type=\"timeoutOrCancel\"}[1m])) / sum(increase(rpc_server_handled_total{env=~\"$env\"}[1m]))",
     "legendFormat": "__auto",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "被调总Panic数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(rpc_server_panic_total{env=~\"$env\"}[$__range]))",
     "legendFormat": "__auto",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CPU使用",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time_seconds_total{env=~\"$env\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time_seconds_total{env=~\"$env\"}[5m])) / sum(process_cpu_cores{env=~\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory使用",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{env=~\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{env=~\"$env\"}/process_memory_quota{env=~\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU配额",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_cores{env=~\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory配额",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_memory_quota{env=~\"$env\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "后端服务", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "服务列表",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "process_cpu_cores{env=~\"$env\"}",
     "legendFormat": "__auto",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "expr": "sum(rate(process_cpu_time_seconds_total{env=~\"$env\"}[5m])) by (app) * 2 / sum(process_cpu_cores{env=~\"$env\"}) by (app)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(process_resident_memory_bytes{env=~\"$env\"}/process_memory_quota{env=~\"$env\"}) by (app)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(rpc_server_handled_total{env=~\"$env\"}[1m])) by (app)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(rpc_server_handled_msec_sum{env=~\"$env\"}[1m]))  by (app) /sum(increase(rpc_server_handled_msec_count{env=~\"$env\"}[1m])) by (app)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1, histogram_quantile(0.99, sum(rate(rpc_server_handled_msec_bucket{env=~\"$env\"}[1m])) by (le, app)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(rpc_server_handled_total{env=~\"$env\", code_type=\"success\"}[1m])) by (app) / sum(increase(rpc_server_handled_total{env=~\"$env\"}[1m])) by (app)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(rpc_client_handled_total{env=~\"$env\"}[1m])) by (app)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(rpc_client_handled_msec_sum{env=~\"$env\"}[1m]))  by (app) /sum(increase(rpc_client_handled_msec_count{env=~\"$env\"}[1m])) by (app)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1, histogram_quantile(0.99, sum(rate(rpc_client_handled_msec_bucket{env=~\"$env\"}[1m])) by (le, app)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(rpc_client_handled_total{env=~\"$env\", code_type=\"success\"}[1m])) by (app) / sum(increase(rpc_client_handled_total{env=~\"$env\"}[1m])) by (app)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "服务状态 Top10", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "异常率曲线 Top10 ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(rpc_server_handled_total{env=~\"$env\", code_type!=\"success\"}[1m])) by (app, instance) / sum(increase(rpc_server_handled_total{env=~\"$env\"}[1m])) by (app, instance))",
     "legendFormat": "{{app}}.{{instance}}"
    }
   ]
  },
  {
   "title": "CPU使用率 Top10",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(process_cpu_time_seconds_total{env=~\"$env\"}[1m])) by (app, instance) * 2 / sum(process_cpu_cores{env=~\"$env\"}) by (app, instance))",
     "legendFormat": "{{app}}.{{instance}}"
    }
   ]
  },
  {
   "title": "内存使用率 Top10",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, process_resident_memory_bytes{env=~\"$env\"}/process_memory_quota{env=~\"$env\"})",
     "legendFormat": "{{app}}.{{instance}}"
    }
   ]
  }
 ]
}